use_gpu: true

data:
    sr: 40000
    shift_ms: 10
    fftl: 2048
    num_mels: 160
    hop_length: 400
    top_db: 120

directories:
    exps: exps/
    dicova_root: DiCOVA/

model:
    name: dummy

pretraining2:
    lr: 0.0001
    future_frames: 10
    hidden_size: 400
    linear_hidden_size: 500
    encoder1_num_layers: 2
    encoder2_num_layers: 2
    batch_first: true
    dropout: 0.1
    log_step: 100
    model_save_step: 500
    num_epochs: 1000
    batch_size: 3
    specaug_probability: 0.0

post_pretraining_classifier:
    lr: 0.0001
    hidden_size: 200
    linear_hidden_size: 300
    encoder_num_layers: 2
    batch_first: true
    dropout: 0.1
    opensmile_dropout: 0.1
    bidirectional: true
    incorrect_scaler: 1
    log_step: 100
    model_save_step: 500
    num_epochs: 1000
    batch_size: 3
    specaug_probability: 1.0

classifier:
    lr: 0.0001
    hidden_size: 200
    linear_hidden_size: 300
    encoder_num_layers: 2
    batch_first: true
    dropout: 0.1
    opensmile_dropout: 0.1
    bidirectional: true
    incorrect_scaler: 1
    log_step: 100
    model_save_step: 500
    num_epochs: 1000
    batch_size: 3
    specaug_probability: 1.0

